# Site settings
title:          xWARE Tech Blog
description:    "Tech Blog by Our Software Engineers"
url:            "https://xwareco.github.io"

# Author
author:
  name:         xWARE Integrated Solutions
  url:          http://www.xware.co
  email:        info@xware.co

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5


timezone: Africa/Cairo

future: false

# Disqus Comments
disqus: xware-tech-blog

# Google Analytics
google_analytics: UA-64809332-2

# Social Media Links

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@xware.co
  facebook: xWARE.Integrated.Solutions
  flickr:
  github: xwareco
  instagram:
  linkedin: xWARE-integrated-solutions
  pinterest:
  rss: anything # just type anything here for a working RSS icon
  twitter: xwareco
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube:  # channel/<your_long_string> or user/<user-name>
  googleplus:  # anything in your profile username that comes after plus.google.com/
