# Site settings
title:          xWARE Tech Blog
description:    "Tech Blog by Our Software Engineers"
url:            "https://xwareco.github.io"

# Author
author:
  name:         xWARE Integrated Solutions
  url:          http://www.xware.co
  email:        info@xware.co

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5


timezone: Africa/Cairo

future: false

# Disqus Comments
disqus: xware-tech-blog

# Google Analytics
google_analytics: UA-64809332-2